// Static reference data generated by tools/build-db.mjs from the LATAM client
// (see README). Loaded once at startup.

import { RAGASSETS_BASE } from "./state";

export type Slot = "top" | "mid" | "low" | "garment";
export const SLOTS: Slot[] = ["top", "mid", "low", "garment"];

export type Costume = {
  id: number;
  name: string;
  /** Sprite view id (the client's ClassNum, or recovered from the resource name
   *  when ClassNum is 0) — absent when the item has none. */
  view?: number;
  /** Visual slot(s) the item occupies (multi-slot costumes cover several). */
  slots: Slot[];
  /** World-effect key (a ".str" aura / falling-petals etc.) for costumes the
   *  character renderer can't draw — rendered in the map sim instead. Assets are
   *  served by ragassets at /effects/<effect>/ (see sim/effect.ts). View-less. */
  effect?: string;
};

export type PaletteInfo = {
  count: number;
  /** Representative hex color per palette index (null when unsampled). */
  swatches: (string | null)[];
};

export type ClassInfo = {
  id: number;
  jt: string;
  name: string;
  group: string;
  race: "human" | "doram";
  /** Clothes-color palettes per gender; a missing gender has no palette files
   *  (gender-locked classes like Trovador/Musa have exactly one entry). */
  palettes: Partial<Record<"m" | "f", PaletteInfo>>;
  /** True when the class has no party icon in the client — unreleased on LATAM. */
  unreleased?: boolean;
};

export type HairSet = {
  styles: { n: number; colors: number }[];
  swatches: (string | null)[];
};

export type HairDb = Record<"human" | "doram", Record<"m" | "f", HairSet>>;

export type Db = {
  classes: ClassInfo[];
  hair: HairDb;
  costumes: Costume[];
};

export async function loadDb(): Promise<Db> {
  const [classes, hair, costumes, effects] = await Promise.all([
    fetchJson<{ classes: ClassInfo[] }>("db/classes.json"),
    fetchJson<HairDb>("db/hair.json"),
    fetchJson<{ items: Costume[] }>("db/costumes.json"),
    // World-effect costumes (auras, falling petals, spotlights — drawn by the
    // client's .str effect system, so view-less and only renderable in the map
    // sim). Served by ragassets (extract-grf.mjs --effects); tolerate failure so
    // a ragassets outage just hides the effect costumes rather than breaking load.
    fetchJson<{ items: Costume[] }>(`${RAGASSETS_BASE}/effects/index.json`).catch(() => ({ items: [] })),
  ]);
  const items = [...costumes.items, ...effects.items]
    .sort((a, b) => a.name.localeCompare(b.name, "pt-BR") || a.id - b.id);
  // Drop classes unreleased on LATAM (no party icon) — they shouldn't appear in
  // the picker (or anywhere else).
  const released = classes.classes.filter((c) => !c.unreleased);
  return { classes: released, hair, costumes: items };
}

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  return res.json() as Promise<T>;
}
